name: Banksys4
version: '${project.version}'
main: com.nessxxiii.banksys4.Banksys4
api-version: 1.18
depend: [Vault]
commands:
  bank:
    description: transfers money from subserver(s) to main server
    usage: /bank transfer