name: Banksys4
version: '${project.version}'
main: com.nessxxiii.banksys4.Banksys4
api-version: 1.18
depend: [Vault]
commands:
  deposit:
    description: deposits money into bank
    usage: /deposit <amount>
  withdraw:
    description: withdraws money from bank
    usage: /withdraw <amount>
  bankbal:
    description: returns a balance
    usage: This command does not require arguments
`